"""Match type definitions for all supported match formats."""

MATCH_TYPES = {
    "standard_singles": {
        "id": "standard_singles",
        "name": "Singles Match",
        "description": "One-on-one competition under standard rules. Pin, submission, or countout.",
        "violence_requirement": 0,
        "injury_multiplier": 1.0,
        "rating_bonus": 0.0,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": False,
        "no_countout": False,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "technical",
    },
    "tag_team": {
        "id": "tag_team",
        "name": "Tag Team Match",
        "description": "Two-on-two action. Tag in your partner to keep fresh and coordinate double-team moves.",
        "violence_requirement": 0,
        "injury_multiplier": 0.9,
        "rating_bonus": 0.1,
        "min_participants": 4,
        "max_participants": 4,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": False,
        "no_countout": False,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "teamwork",
    },
    "triple_threat": {
        "id": "triple_threat",
        "name": "Triple Threat Match",
        "description": "Three competitors, no disqualification. First pinfall or submission wins.",
        "violence_requirement": 2,
        "injury_multiplier": 1.2,
        "rating_bonus": 0.2,
        "min_participants": 3,
        "max_participants": 3,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "chaotic",
    },
    "fatal_four_way": {
        "id": "fatal_four_way",
        "name": "Fatal Four Way",
        "description": "Four competitors collide. No disqualification, no countout. Total chaos.",
        "violence_requirement": 2,
        "injury_multiplier": 1.3,
        "rating_bonus": 0.2,
        "min_participants": 4,
        "max_participants": 4,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "chaotic",
    },
    "steel_cage": {
        "id": "steel_cage",
        "name": "Steel Cage Match",
        "description": "Enclosed in 15 feet of unforgiving steel. Escape over the top or through the door to win.",
        "violence_requirement": 4,
        "injury_multiplier": 1.5,
        "rating_bonus": 0.3,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": False,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "escape_or_pin",
        "narration_flavor": "brutal",
    },
    "ladder": {
        "id": "ladder",
        "name": "Ladder Match",
        "description": "A contract or title hangs above the ring. Climb the ladder and grab it to win.",
        "violence_requirement": 5,
        "injury_multiplier": 1.8,
        "rating_bonus": 0.5,
        "min_participants": 2,
        "max_participants": 8,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "retrieve_object",
        "narration_flavor": "highspot",
    },
    "tables": {
        "id": "tables",
        "name": "Tables Match",
        "description": "Put your opponent through a table to win. The sound of splintering wood is music.",
        "violence_requirement": 4,
        "injury_multiplier": 1.4,
        "rating_bonus": 0.2,
        "min_participants": 2,
        "max_participants": 4,
        "allow_weapons": True,
        "allow_blade": False,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "table_break",
        "narration_flavor": "destruction",
    },
    "tlc": {
        "id": "tlc",
        "name": "TLC Match",
        "description": "Tables, Ladders, and Chairs. All legal, all lethal. Retrieve the prize hanging above.",
        "violence_requirement": 6,
        "injury_multiplier": 2.0,
        "rating_bonus": 0.5,
        "min_participants": 2,
        "max_participants": 8,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "retrieve_object",
        "narration_flavor": "carnage",
    },
    "hardcore": {
        "id": "hardcore",
        "name": "Hardcore Match",
        "description": "No rules. No disqualifications. Falls count anywhere. Anything goes.",
        "violence_requirement": 5,
        "injury_multiplier": 1.6,
        "rating_bonus": 0.2,
        "min_participants": 2,
        "max_participants": 4,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "brutal",
    },
    "last_man_standing": {
        "id": "last_man_standing",
        "name": "Last Man Standing",
        "description": "Beat your opponent so badly they cannot answer the ten count. Brutality is mandatory.",
        "violence_requirement": 6,
        "injury_multiplier": 1.9,
        "rating_bonus": 0.4,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "ten_count",
        "narration_flavor": "endurance",
    },
    "hell_in_a_cell": {
        "id": "hell_in_a_cell",
        "name": "Hell in a Cell",
        "description": "Trapped inside a 20-foot roofed steel structure. Careers end here. Legends are born here.",
        "violence_requirement": 8,
        "injury_multiplier": 2.5,
        "rating_bonus": 0.6,
        "min_participants": 2,
        "max_participants": 4,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "hellacious",
    },
    "barbed_wire": {
        "id": "barbed_wire",
        "name": "Barbed Wire Match",
        "description": "The ropes are replaced with razor-sharp barbed wire. Every bump tears flesh.",
        "violence_requirement": 8,
        "injury_multiplier": 2.3,
        "rating_bonus": 0.3,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "gore",
    },
    "deathmatch": {
        "id": "deathmatch",
        "name": "Deathmatch",
        "description": "Light tubes, thumbtacks, glass panes, barbed wire boards. This is not wrestling. This is war.",
        "violence_requirement": 10,
        "injury_multiplier": 3.0,
        "rating_bonus": 0.2,
        "min_participants": 2,
        "max_participants": 4,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "ultraviolence",
    },
    "iron_man": {
        "id": "iron_man",
        "name": "Iron Man Match",
        "description": "30 or 60 minutes on the clock. Most falls wins. A test of cardio, skill, and heart.",
        "violence_requirement": 1,
        "injury_multiplier": 1.3,
        "rating_bonus": 0.5,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": False,
        "no_countout": False,
        "elimination": False,
        "special_win_condition": "most_falls",
        "narration_flavor": "epic",
    },
    "royal_rumble": {
        "id": "royal_rumble",
        "name": "Royal Rumble",
        "description": "30 competitors enter at timed intervals. Throw them over the top rope. Last one standing wins.",
        "violence_requirement": 3,
        "injury_multiplier": 1.2,
        "rating_bonus": 0.4,
        "min_participants": 20,
        "max_participants": 30,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": True,
        "no_countout": True,
        "elimination": True,
        "special_win_condition": "over_the_top",
        "narration_flavor": "spectacle",
    },
    "battle_royal": {
        "id": "battle_royal",
        "name": "Battle Royal",
        "description": "Everyone starts in the ring. Over the top rope elimination. Last one standing wins it all.",
        "violence_requirement": 2,
        "injury_multiplier": 1.1,
        "rating_bonus": 0.1,
        "min_participants": 6,
        "max_participants": 20,
        "allow_weapons": False,
        "allow_blade": False,
        "no_dq": True,
        "no_countout": True,
        "elimination": True,
        "special_win_condition": "over_the_top",
        "narration_flavor": "spectacle",
    },
    "i_quit": {
        "id": "i_quit",
        "name": "I Quit Match",
        "description": "Make your opponent scream those two words into a microphone. No pins. No submissions. Only surrender.",
        "violence_requirement": 7,
        "injury_multiplier": 2.0,
        "rating_bonus": 0.4,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "verbal_submission",
        "narration_flavor": "torture",
    },
    "street_fight": {
        "id": "street_fight",
        "name": "Street Fight",
        "description": "Come as you are. No rules, no dress code, no mercy. Falls count anywhere.",
        "violence_requirement": 5,
        "injury_multiplier": 1.6,
        "rating_bonus": 0.2,
        "min_participants": 2,
        "max_participants": 4,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "brawl",
    },
    "first_blood": {
        "id": "first_blood",
        "name": "First Blood Match",
        "description": "Make your opponent bleed. First one to draw crimson loses. Every strike could end it.",
        "violence_requirement": 6,
        "injury_multiplier": 1.5,
        "rating_bonus": 0.2,
        "min_participants": 2,
        "max_participants": 2,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": "draw_blood",
        "narration_flavor": "brutal",
    },
    "tables_ladders_chairs": {
        "id": "tables_ladders_chairs",
        "name": "Tables, Ladders & Chairs",
        "description": "The unholy trinity of destruction. Pin or submission with everything legal.",
        "violence_requirement": 6,
        "injury_multiplier": 2.0,
        "rating_bonus": 0.4,
        "min_participants": 2,
        "max_participants": 6,
        "allow_weapons": True,
        "allow_blade": True,
        "no_dq": True,
        "no_countout": True,
        "elimination": False,
        "special_win_condition": None,
        "narration_flavor": "carnage",
    },
}


def get_match_type(match_type_id):
    """Look up a match type by ID. Returns None if not found."""
    return MATCH_TYPES.get(match_type_id)


def is_violent_match(match_type_id):
    """Check if a match type is considered violent (weapons/hardcore)."""
    mt = MATCH_TYPES.get(match_type_id)
    if mt is None:
        return False
    return mt["violence_requirement"] >= 5


def is_multi_person_match(match_type_id):
    """Check if a match type involves more than 2 participants."""
    mt = MATCH_TYPES.get(match_type_id)
    if mt is None:
        return False
    return mt["min_participants"] > 2


def get_match_types_by_violence(max_violence):
    """Return all match types at or below a violence threshold."""
    return {
        k: v for k, v in MATCH_TYPES.items()
        if v["violence_requirement"] <= max_violence
    }
